version: '3.9'

services:
  php-fpm:
    container_name: php-fpm
    image: marcelofabianov/php8.3-fpm:latest
    build:
      context: ./_docker/local/php-fpm
      dockerfile: Dockerfile
    restart: always
    volumes:
      - ./dev/:/var/www
      - ./.zshrc:/home/dev/.zshrc
      - ./.zsh_history:/home/dev/.zsh_history
